import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Button, Card, Col, Form, Row, Table } from "react-bootstrap";
import toast from "react-hot-toast";
import PageHeader from "../../components/common/PageHeader";
import LoadingBlock from "../../components/common/LoadingBlock";
import { reportApi } from "../../api/reportApi";
import { masterApi } from "../../api/masterApi";
import { PO_STATUSES, PO_TYPES, PURCHASE_TYPES } from "../../constants";
import { formatDate, formatMoney } from "../../utils/format";
import { getApiError } from "../../utils/error";

export default function ReportsPage(){
  const [f,setF]=useState({dateFrom:"",dateTo:"",vendorId:"",projectId:"",costCenterId:"",status:"",poType:"",purchaseType:""});
  const params=useMemo(()=>Object.fromEntries(Object.entries(f).filter(([,v])=>v!=="")),[f]);
  const q=useQuery({queryKey:["po-report",params],queryFn:()=>reportApi.list(params)});const vendors=useQuery({queryKey:["select","vendors-report"],queryFn:()=>masterApi.list("/vendors",{isActive:true,limit:200})});const projects=useQuery({queryKey:["select","projects-report"],queryFn:()=>masterApi.list("/projects",{isActive:true,limit:200})});const cc=useQuery({queryKey:["select","cc-report"],queryFn:()=>masterApi.list("/cost-centers",{isActive:true,limit:200})});
  const rows=q.data?.data||[];const total=rows.reduce((s,r)=>s+Number(r.totals?.grandTotal||0),0);
  async function exportCsv(){try{const blob=await reportApi.exportCsv(params);const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`purchase-order-report-${Date.now()}.csv`;a.click();URL.revokeObjectURL(url);}catch(e){toast.error(getApiError(e))}}
  return <><PageHeader title="Purchase Order Reports" subtitle="Filter PO data by date, vendor, project, status and type." actions={<Button variant="outline-success" onClick={exportCsv}><i className="bi bi-file-earmark-spreadsheet me-2"/>Export CSV</Button>}/><Card className="border-0 shadow-sm mb-3"><Card.Body className="p-4"><Row className="g-2">{[["dateFrom","From","date"],["dateTo","To","date"]].map(([k,l,t])=><Col md={2} key={k}><Form.Label>{l}</Form.Label><Form.Control type={t} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/></Col>)}<Col md={3}><Form.Label>Vendor</Form.Label><Form.Select value={f.vendorId} onChange={e=>setF({...f,vendorId:e.target.value})}><option value="">All</option>{(vendors.data?.data||[]).map(x=><option key={x._id} value={x._id}>{x.vendorCode} - {x.vendorName}</option>)}</Form.Select></Col><Col md={3}><Form.Label>Project</Form.Label><Form.Select value={f.projectId} onChange={e=>setF({...f,projectId:e.target.value})}><option value="">All</option>{(projects.data?.data||[]).map(x=><option key={x._id} value={x._id}>{x.projectCode}</option>)}</Form.Select></Col><Col md={2}><Form.Label>Cost Center</Form.Label><Form.Select value={f.costCenterId} onChange={e=>setF({...f,costCenterId:e.target.value})}><option value="">All</option>{(cc.data?.data||[]).map(x=><option key={x._id} value={x._id}>{x.costCenterCode}</option>)}</Form.Select></Col><Col md={3}><Form.Label>Status</Form.Label><Form.Select value={f.status} onChange={e=>setF({...f,status:e.target.value})}><option value="">All</option>{PO_STATUSES.map(x=><option key={x}>{x}</option>)}</Form.Select></Col><Col md={3}><Form.Label>PO Type</Form.Label><Form.Select value={f.poType} onChange={e=>setF({...f,poType:e.target.value})}><option value="">All</option>{PO_TYPES.map(x=><option key={x}>{x}</option>)}</Form.Select></Col><Col md={3}><Form.Label>Purchase Type</Form.Label><Form.Select value={f.purchaseType} onChange={e=>setF({...f,purchaseType:e.target.value})}><option value="">All</option>{PURCHASE_TYPES.map(x=><option key={x}>{x}</option>)}</Form.Select></Col><Col md={3} className="d-flex align-items-end"><Button variant="outline-secondary" className="w-100" onClick={()=>setF({dateFrom:"",dateTo:"",vendorId:"",projectId:"",costCenterId:"",status:"",poType:"",purchaseType:""})}>Clear Filters</Button></Col></Row></Card.Body></Card>
  <Row className="g-3 mb-3"><Col md={4}><Card className="border-0 shadow-sm"><Card.Body><div className="small text-secondary">Matching POs</div><div className="h3 fw-bold mb-0">{rows.length}</div></Card.Body></Card></Col><Col md={8}><Card className="border-0 shadow-sm"><Card.Body><div className="small text-secondary">Combined Grand Total</div><div className="h3 fw-bold mb-0">{formatMoney(total)}</div></Card.Body></Card></Col></Row>
  <Card className="border-0 shadow-sm"><Card.Body className="p-0">{q.isLoading?<LoadingBlock/>:<div className="table-responsive"><Table hover className="align-middle mb-0"><thead className="table-light"><tr><th className="ps-4">PO</th><th>Date</th><th>Vendor</th><th>Project</th><th>Cost Center</th><th>Type</th><th className="text-end">Subtotal</th><th className="text-end">Tax</th><th className="text-end">Grand Total</th><th>Status</th></tr></thead><tbody>{rows.map(po=><tr key={po._id}><td className="ps-4">{po.poNumber}{po.revisionNo?` / R${po.revisionNo}`:""}</td><td>{formatDate(po.poDate)}</td><td>{po.vendor?.vendorName}</td><td>{po.project?.projectCode||"-"}</td><td>{po.costCenter?.costCenterCode}</td><td>{po.poType}</td><td className="text-end">{formatMoney(po.totals?.subTotal,po.currency)}</td><td className="text-end">{formatMoney(po.totals?.taxTotal,po.currency)}</td><td className="text-end fw-semibold">{formatMoney(po.totals?.grandTotal,po.currency)}</td><td>{po.status}</td></tr>)}</tbody></Table></div>}</Card.Body></Card></>;
}
