import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Button, Card, Col, Form, Modal, Row, Table } from "react-bootstrap";
import toast from "react-hot-toast";
import PageHeader from "../../components/common/PageHeader";
import { masterApi } from "../../api/masterApi";
import { ALL_PERMISSIONS } from "../../constants";
import { getApiError } from "../../utils/error";
import LoadingBlock from "../../components/common/LoadingBlock";
import PermissionGate from "../../components/auth/PermissionGate";

const initial = { roleName: "", permissions: [], approvalLimit: "", isActive: true };
export default function RolesPage() {
  const qc = useQueryClient();
  const [show,setShow]=useState(false); const [editing,setEditing]=useState(null); const [form,setForm]=useState(initial);
  const q=useQuery({queryKey:["roles"],queryFn:()=>masterApi.list("/roles",{limit:200})});
  const save=useMutation({mutationFn:(p)=>editing?masterApi.update("/roles",editing._id,p):masterApi.create("/roles",p),onSuccess:()=>{toast.success("Role saved");setShow(false);qc.invalidateQueries({queryKey:["roles"]});},onError:(e)=>toast.error(getApiError(e))});
  const status=useMutation({mutationFn:({id,a})=>masterApi.setStatus("/roles",id,a),onSuccess:()=>qc.invalidateQueries({queryKey:["roles"]}),onError:(e)=>toast.error(getApiError(e))});
  function open(r){setEditing(r||null);setForm(r?{...r,approvalLimit:r.approvalLimit??""}:initial);setShow(true)}
  function toggle(p){setForm((f)=>({...f,permissions:f.permissions.includes(p)?f.permissions.filter(x=>x!==p):[...f.permissions,p]}))}
  function submit(e){e.preventDefault();const p={...form,approvalLimit:form.approvalLimit===""?null:Number(form.approvalLimit)};delete p._id;delete p.__v;delete p.createdAt;delete p.updatedAt;save.mutate(p)}
  return <><PageHeader title="Role & Permission Master" subtitle="Control access to masters, PO workflow and reports." actions={<PermissionGate any={["role.write"]}><Button onClick={()=>open()}><i className="bi bi-plus-lg me-2"/>Add Role</Button></PermissionGate>}/><Card className="border-0 shadow-sm"><Card.Body className="p-4">{q.isLoading?<LoadingBlock/>:<div className="table-responsive"><Table hover className="align-middle"><thead className="table-light"><tr><th>Role</th><th>Permissions</th><th>Approval Limit</th><th>Status</th><th className="text-end">Action</th></tr></thead><tbody>{(q.data?.data||[]).map(r=><tr key={r._id}><td className="fw-semibold">{r.roleName}</td><td>{r.permissions?.includes("*")?"All permissions":`${r.permissions?.length||0} permission(s)`}</td><td>{r.approvalLimit??"No limit"}</td><td><span className={`badge ${r.isActive?"text-bg-success":"text-bg-secondary"}`}>{r.isActive?"Active":"Inactive"}</span></td><td className="text-end"><PermissionGate any={["role.write"]}><Button size="sm" variant="outline-primary" className="me-2" onClick={()=>open(r)}><i className="bi bi-pencil"/></Button><Button size="sm" variant={r.isActive?"outline-danger":"outline-success"} onClick={()=>status.mutate({id:r._id,a:!r.isActive})}><i className={`bi ${r.isActive?"bi-pause-circle":"bi-play-circle"}`}/></Button></PermissionGate></td></tr>)}</tbody></Table></div>}</Card.Body></Card>
  <Modal show={show} onHide={()=>setShow(false)} size="xl" centered scrollable><Form onSubmit={submit}><Modal.Header closeButton><Modal.Title>{editing?"Edit":"Add"} Role</Modal.Title></Modal.Header><Modal.Body><Row className="g-3 mb-3"><Col md={6}><Form.Label>Role Name</Form.Label><Form.Control required value={form.roleName} onChange={e=>setForm({...form,roleName:e.target.value})}/></Col><Col md={6}><Form.Label>Approval Limit</Form.Label><Form.Control type="number" min="0" placeholder="Blank = no limit" value={form.approvalLimit} onChange={e=>setForm({...form,approvalLimit:e.target.value})}/></Col></Row><div className="d-flex justify-content-between align-items-center mb-2"><strong>Permissions</strong><div><Button type="button" size="sm" variant="outline-primary" className="me-2" onClick={()=>setForm({...form,permissions:["*"]})}>Grant All (*)</Button><Button type="button" size="sm" variant="outline-secondary" onClick={()=>setForm({...form,permissions:[]})}>Clear</Button></div></div>{form.permissions.includes("*")?<div className="alert alert-info">This role has <strong>*</strong> and therefore has access to all current and future permissions.</div>:<Row className="g-2">{ALL_PERMISSIONS.map(p=><Col sm={6} md={4} key={p}><Form.Check type="checkbox" checked={form.permissions.includes(p)} label={p} onChange={()=>toggle(p)}/></Col>)}</Row>}</Modal.Body><Modal.Footer><Button variant="outline-secondary" onClick={()=>setShow(false)}>Cancel</Button><Button type="submit" disabled={save.isPending}>Save Role</Button></Modal.Footer></Form></Modal></>;
}
